using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace RazorBlade.SourceGenerator;

/// <summary>
/// Generates C# code from parsed Razor components.
/// </summary>
public class RazorComponentCodeGenerator
{
    public string Generate(ParsedComponent component, string className, string namespaceName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Add usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading.Tasks;");
        
        // Add RazorBlade using if not already in component usings
        if (!component.Usings.Contains("RazorBlade"))
        {
            sb.AppendLine("using RazorBlade;");
        }
        
        foreach (var u in component.Usings)
        {
            sb.AppendLine($"using {u};");
        }
        
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className} : {component.BaseClass}");
        sb.AppendLine("    {");

        // Add properties from code block (but filter out [Parameter] decorated ones as we'll add them)
        var codeBlockWithoutParameters = RemoveParameterProperties(component.CodeBlock);
        if (!string.IsNullOrWhiteSpace(codeBlockWithoutParameters))
        {
            foreach (var line in codeBlockWithoutParameters.Split('\n'))
            {
                if (!string.IsNullOrWhiteSpace(line))
                    sb.AppendLine($"        {line}");
            }
        }

        // Add parameter properties
        foreach (var param in component.Parameters)
        {
            if (param.DefaultValue != null)
            {
                sb.AppendLine($"        public {param.Type} {param.Name} {{ get; set; }} = {param.DefaultValue};");
            }
            else
            {
                sb.AppendLine($"        public {param.Type} {param.Name} {{ get; set; }} = default!;");
            }
        }

        if (component.Parameters.Count > 0)
            sb.AppendLine();

        // Generate ExecuteAsync method
        sb.AppendLine("        protected override Task ExecuteAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            // Synchronous rendering");
        sb.AppendLine();

        // Process markup and convert to C# code
        var markupCode = ConvertMarkupToCode(component.MarkupContent);
        sb.Append(markupCode);

        sb.AppendLine("            return Task.CompletedTask;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private string RemoveParameterProperties(string codeBlock)
    {
        if (string.IsNullOrWhiteSpace(codeBlock))
            return string.Empty;

        // Remove lines with [Parameter] and the following property declaration
        var lines = codeBlock.Split('\n');
        var result = new StringBuilder();
        var skipNext = false;

        foreach (var line in lines)
        {
            if (skipNext)
            {
                skipNext = false;
                continue;
            }

            if (line.Trim().StartsWith("[Parameter]"))
            {
                skipNext = true;
                continue;
            }

            result.AppendLine(line);
        }

        return result.ToString();
    }

    private string ConvertMarkupToCode(string markup)
    {
        var sb = new StringBuilder();
        var lines = markup.Split('\n');
        var indent = "            ";

        foreach (var line in lines)
        {
            var trimmedLine = line.Trim();
            
            // Skip empty lines, directives, and comments
            if (string.IsNullOrWhiteSpace(trimmedLine) ||
                trimmedLine.StartsWith("@using") ||
                trimmedLine.StartsWith("@inherits") ||
                trimmedLine.StartsWith("@*"))
                continue;

            if (trimmedLine == "*@")
                continue;

            // Process the line and generate Write/WriteLiteral calls
            ProcessMarkupLine(trimmedLine, sb, indent);
        }

        return sb.ToString();
    }

    private void ProcessMarkupLine(string line, StringBuilder output, string indent)
    {
        var i = 0;
        var literalBuffer = new StringBuilder();

        while (i < line.Length)
        {
            // Check for @ expressions
            if (line[i] == '@')
            {
                // Output any accumulated literal content
                if (literalBuffer.Length > 0)
                {
                    output.AppendLine($"{indent}WriteLiteral(\"{EscapeString(literalBuffer.ToString())}\");");
                    literalBuffer.Clear();
                }

                i++; // Skip the @
                
                // @@ escapes to single @
                if (i < line.Length && line[i] == '@')
                {
                    literalBuffer.Append('@');
                    i++;
                    continue;
                }

                // @ followed by control structure
                if (i < line.Length && char.IsLetter(line[i]))
                {
                    // Check for @if, @foreach, @for, @while, etc.
                    var keyword = ExtractKeyword(line, i);
                    if (keyword == "if" || keyword == "foreach" || keyword == "for" || keyword == "while")
                    {
                        // Extract the condition/expression up to {
                        var startPos = i + keyword.Length;
                        var endPos = line.IndexOf('{', startPos);
                        if (endPos > 0)
                        {
                            var condition = line.Substring(startPos, endPos - startPos).Trim();
                            output.AppendLine($"{indent}{keyword} ({condition})");
                            output.AppendLine($"{indent}{{");
                            i = endPos + 1;
                            continue;
                        }
                    }
                    else if (line[i] == '}')
                    {
                        // Closing brace
                        output.AppendLine($"{indent}}}");
                        i++;
                        continue;
                    }
                }

                // Extract expression
                var expr = ExtractExpression(line, i);
                if (!string.IsNullOrEmpty(expr.Expression))
                {
                    output.AppendLine($"{indent}Write({expr.Expression});");
                    i = expr.EndIndex;
                }
            }
            else if (line[i] == '}' && literalBuffer.Length == 0)
            {
                // Standalone closing brace (from @if, @foreach, etc.)
                output.AppendLine($"{indent}}}");
                i++;
            }
            else if (line[i] == '{' && i > 0 && line[i-1] != '@')
            {
                // Opening brace (from @if, @foreach, etc.) - already handled above
                i++;
            }
            else
            {
                // Regular character - add to literal buffer
                literalBuffer.Append(line[i]);
                i++;
            }
        }

        // Output any remaining literal content
        if (literalBuffer.Length > 0)
        {
            output.AppendLine($"{indent}WriteLiteral(\"{EscapeString(literalBuffer.ToString())}\");");
        }
    }

    private string ExtractKeyword(string line, int start)
    {
        var sb = new StringBuilder();
        var i = start;
        while (i < line.Length && char.IsLetter(line[i]))
        {
            sb.Append(line[i]);
            i++;
        }
        return sb.ToString();
    }

    private (string Expression, int EndIndex) ExtractExpression(string line, int start)
    {
        var sb = new StringBuilder();
        var i = start;

        // Check if it's a parenthesized expression
        if (i < line.Length && line[i] == '(')
        {
            var parenCount = 1;
            sb.Append(line[i]);
            i++;

            while (i < line.Length && parenCount > 0)
            {
                if (line[i] == '(') parenCount++;
                else if (line[i] == ')') parenCount--;
                sb.Append(line[i]);
                i++;
            }

            return (sb.ToString(), i);
        }

        // Simple identifier or member access
        while (i < line.Length && (char.IsLetterOrDigit(line[i]) || line[i] == '_' || line[i] == '.'))
        {
            sb.Append(line[i]);
            i++;
        }

        return (sb.ToString(), i);
    }

    private string EscapeString(string str)
    {
        return str.Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
    }
}
